# Generated by Django 4.2.7 on 2025-08-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_medicine_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_time',
            new_name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='card', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.JSONField(default=dict),
        ),
    ]
