# Generated by Django 4.2.7 on 2025-08-21 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_price_at_time_orderitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Account'), ('wallet', 'Digital Wallet')], default='card', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('masked_number', models.CharField(max_length=50)),
                ('encrypted_number', models.TextField()),
                ('expiry_date', models.CharField(blank=True, max_length=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
