# Generated by Django 4.2.7 on 2025-08-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='encrypted_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
