# Generated by Django 4.2.7 on 2025-08-25 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ambulance_recordings/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('enroute', 'En route'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('eta_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_requests', to='core.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambulance_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
