# Generated by Django 4.2.7 on 2025-08-26 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ambulancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('settings_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('show_profile_to_doctors', models.BooleanField(default=True)),
                ('show_contact_info_to_doctors', models.BooleanField(default=False)),
                ('allow_marketing_emails', models.BooleanField(default=False)),
                ('share_anonymized_analytics', models.BooleanField(default=False)),
                ('allow_chat_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_settings',
            },
        ),
    ]
