# Generated by Django 4.2.7 on 2025-08-26 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_privacysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSecurity',
            fields=[
                ('security_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_totp_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, max_length=64, null=True)),
                ('backup_code_hashes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_security',
            },
        ),
    ]
