# Generated by Django 4.2.7 on 2025-09-09 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointment_paid_at_appointment_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('vital_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.patient')),
            ],
            options={
                'db_table': 'vital_signs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('symptom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('onset_date', models.DateField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='core.patient')),
            ],
            options={
                'db_table': 'symptom_entries',
                'ordering': ['-onset_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicationRecord',
            fields=[
                ('med_record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_records', to='core.patient')),
            ],
            options={
                'db_table': 'patient_medications',
                'ordering': ['-is_active', '-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('lab_result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('result_value', models.CharField(max_length=255)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='core.patient')),
            ],
            options={
                'db_table': 'lab_results',
                'ordering': ['-recorded_at', 'test_name'],
            },
        ),
        migrations.CreateModel(
            name='DnaTest',
            fields=[
                ('dna_test_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('trait', models.CharField(blank=True, max_length=255)),
                ('interpretation', models.TextField(blank=True)),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_tests', to='core.patient')),
            ],
            options={
                'db_table': 'dna_tests',
                'ordering': ['-recorded_at', 'test_name'],
            },
        ),
    ]
