from decimal import Decimal
from django.core.management.base import BaseCommand
from core.models import Medicine


class Command(BaseCommand):
    help = "Seed pharmacy medicines (idempotent)"

    def handle(self, *args, **options):
        medicines = [
            {
                "name": "Paracetamol",
                "generic_name": "Acetaminophen",
                "description": "Pain reliever and fever reducer.",
                "dosage_form": "Tablet",
                "strength": "500mg",
                "manufacturer": "Panado",
                "price": Decimal("29.99"),
                "original_price": Decimal("39.99"),
                "stock_quantity": 200,
                "image_url": "https://dummyimage.com/600x400/edf2f7/1a202c.png&text=Paracetamol+500mg",
                "is_prescription_required": False,
                "category": "Pain Relief",
            },
            {
                "name": "Ibuprofen",
                "generic_name": "Ibuprofen",
                "description": "NSAID used for pain, fever, and inflammation.",
                "dosage_form": "Tablet",
                "strength": "400mg",
                "manufacturer": "Advil",
                "price": Decimal("49.99"),
                "original_price": Decimal("59.99"),
                "stock_quantity": 150,
                "image_url": "https://dummyimage.com/600x400/e6fffa/234e52.png&text=Ibuprofen+400mg",
                "is_prescription_required": False,
                "category": "Pain Relief",
            },
            {
                "name": "Amoxicillin",
                "generic_name": "Amoxicillin",
                "description": "Antibiotic for bacterial infections.",
                "dosage_form": "Capsule",
                "strength": "500mg",
                "manufacturer": "Sandoz",
                "price": Decimal("89.99"),
                "original_price": None,
                "stock_quantity": 80,
                "image_url": "https://dummyimage.com/600x400/fff5f5/742a2a.png&text=Amoxicillin+500mg",
                "is_prescription_required": True,
                "category": "Antibiotics",
            },
            {
                "name": "Cetirizine",
                "generic_name": "Cetirizine",
                "description": "Antihistamine for allergy relief.",
                "dosage_form": "Tablet",
                "strength": "10mg",
                "manufacturer": "Zyrtec",
                "price": Decimal("39.99"),
                "original_price": Decimal("49.99"),
                "stock_quantity": 120,
                "image_url": "https://dummyimage.com/600x400/ebf8ff/1a365d.png&text=Cetirizine+10mg",
                "is_prescription_required": False,
                "category": "Allergies",
            },
            {
                "name": "Omeprazole",
                "generic_name": "Omeprazole",
                "description": "Proton pump inhibitor for acid reflux.",
                "dosage_form": "Capsule",
                "strength": "20mg",
                "manufacturer": "AstraZeneca",
                "price": Decimal("79.99"),
                "original_price": None,
                "stock_quantity": 90,
                "image_url": "https://dummyimage.com/600x400/f0fff4/22543d.png&text=Omeprazole+20mg",
                "is_prescription_required": False,
                "category": "Gastrointestinal",
            },
            {
                "name": "Azithromycin",
                "generic_name": "Azithromycin",
                "description": "Macrolide antibiotic for various infections.",
                "dosage_form": "Tablet",
                "strength": "500mg",
                "manufacturer": "Pfizer",
                "price": Decimal("119.99"),
                "original_price": Decimal("129.99"),
                "stock_quantity": 60,
                "image_url": "https://dummyimage.com/600x400/fffaf0/7b341e.png&text=Azithromycin+500mg",
                "is_prescription_required": True,
                "category": "Antibiotics",
            },
            {
                "name": "Metformin",
                "generic_name": "Metformin",
                "description": "First-line therapy for type 2 diabetes.",
                "dosage_form": "Tablet",
                "strength": "500mg",
                "manufacturer": "Merck",
                "price": Decimal("59.99"),
                "original_price": Decimal("69.99"),
                "stock_quantity": 140,
                "image_url": "https://dummyimage.com/600x400/edf2f7/2d3748.png&text=Metformin+500mg",
                "is_prescription_required": True,
                "category": "Diabetes",
            },
            {
                "name": "Gliclazide",
                "generic_name": "Gliclazide",
                "description": "Sulfonylurea for type 2 diabetes.",
                "dosage_form": "Tablet",
                "strength": "80mg",
                "manufacturer": "Servier",
                "price": Decimal("69.99"),
                "original_price": None,
                "stock_quantity": 75,
                "image_url": "https://dummyimage.com/600x400/fff5f5/4a5568.png&text=Gliclazide+80mg",
                "is_prescription_required": True,
                "category": "Diabetes",
            },
            {
                "name": "Amlodipine",
                "generic_name": "Amlodipine",
                "description": "Calcium-channel blocker for hypertension.",
                "dosage_form": "Tablet",
                "strength": "5mg",
                "manufacturer": "Pfizer",
                "price": Decimal("49.99"),
                "original_price": Decimal("59.99"),
                "stock_quantity": 110,
                "image_url": "https://dummyimage.com/600x400/f7fafc/1a202c.png&text=Amlodipine+5mg",
                "is_prescription_required": True,
                "category": "Hypertension",
            },
            {
                "name": "Losartan",
                "generic_name": "Losartan",
                "description": "ARB antihypertensive agent.",
                "dosage_form": "Tablet",
                "strength": "50mg",
                "manufacturer": "MSD",
                "price": Decimal("79.99"),
                "original_price": None,
                "stock_quantity": 95,
                "image_url": "https://dummyimage.com/600x400/ebf8ff/2a4365.png&text=Losartan+50mg",
                "is_prescription_required": True,
                "category": "Hypertension",
            },
            {
                "name": "Atorvastatin",
                "generic_name": "Atorvastatin",
                "description": "Statin for cholesterol reduction.",
                "dosage_form": "Tablet",
                "strength": "20mg",
                "manufacturer": "Pfizer",
                "price": Decimal("99.99"),
                "original_price": Decimal("109.99"),
                "stock_quantity": 85,
                "image_url": "https://dummyimage.com/600x400/fffaf0/2d3748.png&text=Atorvastatin+20mg",
                "is_prescription_required": True,
                "category": "Cholesterol",
            },
            {
                "name": "Vitamin C",
                "generic_name": "Ascorbic Acid",
                "description": "Antioxidant vitamin supplement.",
                "dosage_form": "Tablet",
                "strength": "1000mg",
                "manufacturer": "Solgar",
                "price": Decimal("39.99"),
                "original_price": Decimal("49.99"),
                "stock_quantity": 220,
                "image_url": "https://dummyimage.com/600x400/fffff0/2f855a.png&text=Vitamin+C+1000mg",
                "is_prescription_required": False,
                "category": "Vitamins",
            },
            {
                "name": "Vitamin D3",
                "generic_name": "Cholecalciferol",
                "description": "Supports bone health and immunity.",
                "dosage_form": "Softgel",
                "strength": "1000 IU",
                "manufacturer": "Now Foods",
                "price": Decimal("34.99"),
                "original_price": None,
                "stock_quantity": 180,
                "image_url": "https://dummyimage.com/600x400/f0fff4/234e52.png&text=Vitamin+D3+1000IU",
                "is_prescription_required": False,
                "category": "Vitamins",
            },
            {
                "name": "Zinc",
                "generic_name": "Zinc Gluconate",
                "description": "Mineral supplement supporting immunity.",
                "dosage_form": "Tablet",
                "strength": "50mg",
                "manufacturer": "Nature Made",
                "price": Decimal("29.99"),
                "original_price": None,
                "stock_quantity": 160,
                "image_url": "https://dummyimage.com/600x400/edf2f7/2b6cb0.png&text=Zinc+50mg",
                "is_prescription_required": False,
                "category": "Vitamins",
            },
            {
                "name": "Loratadine",
                "generic_name": "Loratadine",
                "description": "Non-drowsy antihistamine.",
                "dosage_form": "Tablet",
                "strength": "10mg",
                "manufacturer": "Claritin",
                "price": Decimal("34.99"),
                "original_price": Decimal("44.99"),
                "stock_quantity": 130,
                "image_url": "https://dummyimage.com/600x400/ebf8ff/234e52.png&text=Loratadine+10mg",
                "is_prescription_required": False,
                "category": "Allergies",
            },
            {
                "name": "Dextromethorphan",
                "generic_name": "Dextromethorphan",
                "description": "Cough suppressant for dry cough.",
                "dosage_form": "Syrup",
                "strength": "15mg/5ml",
                "manufacturer": "Vicks",
                "price": Decimal("54.99"),
                "original_price": None,
                "stock_quantity": 100,
                "image_url": "https://dummyimage.com/600x400/e6fffb/234e52.png&text=Dextromethorphan+syrup",
                "is_prescription_required": False,
                "category": "Cold & Flu",
            },
            {
                "name": "Salbutamol Inhaler",
                "generic_name": "Albuterol",
                "description": "Short-acting bronchodilator for asthma relief.",
                "dosage_form": "Inhaler",
                "strength": "100mcg/dose",
                "manufacturer": "GSK",
                "price": Decimal("129.99"),
                "original_price": Decimal("139.99"),
                "stock_quantity": 70,
                "image_url": "https://dummyimage.com/600x400/edf2f7/742a2a.png&text=Salbutamol+Inhaler",
                "is_prescription_required": True,
                "category": "Respiratory",
            },
            {
                "name": "Hydrocortisone Cream",
                "generic_name": "Hydrocortisone",
                "description": "Topical steroid for itchy, inflamed skin.",
                "dosage_form": "Cream",
                "strength": "1%",
                "manufacturer": "Teva",
                "price": Decimal("44.99"),
                "original_price": None,
                "stock_quantity": 90,
                "image_url": "https://dummyimage.com/600x400/fff5f5/1a202c.png&text=Hydrocortisone+1%25",
                "is_prescription_required": False,
                "category": "Dermatology",
            },
            {
                "name": "Lansoprazole",
                "generic_name": "Lansoprazole",
                "description": "PPI for ulcers and GERD.",
                "dosage_form": "Capsule",
                "strength": "30mg",
                "manufacturer": "Takeda",
                "price": Decimal("89.99"),
                "original_price": None,
                "stock_quantity": 75,
                "image_url": "https://dummyimage.com/600x400/f0fff4/22543d.png&text=Lansoprazole+30mg",
                "is_prescription_required": True,
                "category": "Gastrointestinal",
            },
            {
                "name": "Aspirin EC",
                "generic_name": "Acetylsalicylic Acid",
                "description": "Enteric-coated aspirin for pain and cardioprotection (per guidance).",
                "dosage_form": "Tablet (EC)",
                "strength": "81mg",
                "manufacturer": "Bayer",
                "price": Decimal("24.99"),
                "original_price": Decimal("29.99"),
                "stock_quantity": 210,
                "image_url": "https://dummyimage.com/600x400/ebf8ff/1a202c.png&text=Aspirin+EC+81mg",
                "is_prescription_required": False,
                "category": "Pain Relief",
            },
            {
                "name": "Folic Acid",
                "generic_name": "Folic Acid",
                "description": "Supplement recommended during pregnancy and for deficiency.",
                "dosage_form": "Tablet",
                "strength": "5mg",
                "manufacturer": "Aspen",
                "price": Decimal("19.99"),
                "original_price": None,
                "stock_quantity": 230,
                "image_url": "https://dummyimage.com/600x400/fffff0/234e52.png&text=Folic+Acid+5mg",
                "is_prescription_required": False,
                "category": "Vitamins",
            },
            {
                "name": "Amoxicillin-Clavulanate",
                "generic_name": "Amoxicillin/Clavulanic Acid",
                "description": "Broad-spectrum antibiotic combination.",
                "dosage_form": "Tablet",
                "strength": "875mg/125mg",
                "manufacturer": "Sandoz",
                "price": Decimal("149.99"),
                "original_price": Decimal("159.99"),
                "stock_quantity": 55,
                "image_url": "https://dummyimage.com/600x400/fff5f5/2d3748.png&text=Amox-Clav+875/125",
                "is_prescription_required": True,
                "category": "Antibiotics",
            },
            {
                "name": "Eye Drops (Lubricant)",
                "generic_name": "Hydroxypropyl Methylcellulose",
                "description": "Artificial tears for dry eye relief.",
                "dosage_form": "Drops",
                "strength": "0.3%",
                "manufacturer": "Allergan",
                "price": Decimal("59.99"),
                "original_price": None,
                "stock_quantity": 100,
                "image_url": "https://dummyimage.com/600x400/ebf8ff/2d3748.png&text=Lubricant+Eye+Drops",
                "is_prescription_required": False,
                "category": "Ophthalmology",
            },
            {
                "name": "Naproxen",
                "generic_name": "Naproxen",
                "description": "NSAID for pain and inflammation.",
                "dosage_form": "Tablet",
                "strength": "500mg",
                "manufacturer": "Aleve",
                "price": Decimal("69.99"),
                "original_price": Decimal("79.99"),
                "stock_quantity": 120,
                "image_url": "https://dummyimage.com/600x400/edf2f7/234e52.png&text=Naproxen+500mg",
                "is_prescription_required": False,
                "category": "Pain Relief",
            },
            {
                "name": "Diclofenac Gel",
                "generic_name": "Diclofenac",
                "description": "Topical NSAID gel for joint pain.",
                "dosage_form": "Gel",
                "strength": "1%",
                "manufacturer": "Novartis",
                "price": Decimal("64.99"),
                "original_price": None,
                "stock_quantity": 90,
                "image_url": "https://dummyimage.com/600x400/f7fafc/2d3748.png&text=Diclofenac+Gel+1%25",
                "is_prescription_required": False,
                "category": "Pain Relief",
            },
            {
                "name": "Captopril",
                "generic_name": "Captopril",
                "description": "ACE inhibitor for hypertension.",
                "dosage_form": "Tablet",
                "strength": "25mg",
                "manufacturer": "Hexal",
                "price": Decimal("34.99"),
                "original_price": None,
                "stock_quantity": 100,
                "image_url": "https://dummyimage.com/600x400/ebf8ff/1a202c.png&text=Captopril+25mg",
                "is_prescription_required": True,
                "category": "Hypertension",
            },
            {
                "name": "Insulin Glargine",
                "generic_name": "Insulin Glargine",
                "description": "Long-acting insulin for diabetes.",
                "dosage_form": "Injection",
                "strength": "100 IU/ml",
                "manufacturer": "Sanofi",
                "price": Decimal("299.99"),
                "original_price": Decimal("319.99"),
                "stock_quantity": 30,
                "image_url": "https://dummyimage.com/600x400/fffaf0/2d3748.png&text=Insulin+Glargine",
                "is_prescription_required": True,
                "category": "Diabetes",
            },
            {
                "name": "Clotrimazole Cream",
                "generic_name": "Clotrimazole",
                "description": "Antifungal cream for skin infections.",
                "dosage_form": "Cream",
                "strength": "1%",
                "manufacturer": "Bayer",
                "price": Decimal("39.99"),
                "original_price": None,
                "stock_quantity": 100,
                "image_url": "https://dummyimage.com/600x400/fff5f5/234e52.png&text=Clotrimazole+1%25",
                "is_prescription_required": False,
                "category": "Dermatology",
            },
            {
                "name": "Oral Rehydration Salts",
                "generic_name": "ORS",
                "description": "Replaces fluids and electrolytes.",
                "dosage_form": "Powder",
                "strength": "WHO formula",
                "manufacturer": "WHO",
                "price": Decimal("14.99"),
                "original_price": None,
                "stock_quantity": 300,
                "image_url": "https://dummyimage.com/600x400/e6fffa/2d3748.png&text=ORS+Sachets",
                "is_prescription_required": False,
                "category": "Gastrointestinal",
            },
            {
                "name": "Probiotic Capsules",
                "generic_name": "Lactobacillus Blend",
                "description": "Supports gut health and digestion.",
                "dosage_form": "Capsule",
                "strength": "10 Billion CFU",
                "manufacturer": "Culturelle",
                "price": Decimal("99.99"),
                "original_price": Decimal("109.99"),
                "stock_quantity": 80,
                "image_url": "https://dummyimage.com/600x400/f0fff4/2d3748.png&text=Probiotic+Capsules",
                "is_prescription_required": False,
                "category": "Gastrointestinal",
            },
        ]

        created = 0
        updated = 0
        for data in medicines:
            obj, was_created = Medicine.objects.update_or_create(
                name=data["name"],
                defaults={
                    "generic_name": data.get("generic_name", ""),
                    "description": data.get("description", ""),
                    "dosage_form": data.get("dosage_form", ""),
                    "strength": data.get("strength", ""),
                    "manufacturer": data.get("manufacturer", ""),
                    "price": data.get("price"),
                    "original_price": data.get("original_price"),
                    "stock_quantity": data.get("stock_quantity", 0),
                    "image_url": data.get("image_url", ""),
                    "is_prescription_required": data.get("is_prescription_required", False),
                    "category": data.get("category", "General"),
                },
            )
            if was_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(f"Medicines seeded. Created: {created}, Updated: {updated}"))


